# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
#     branches: [ master ]
  pull_request:
#     branches: [ master ]


#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
# #     - run: npm ci
# #     - run: npm run build --if-present
# #     - run: npm test

# #     - name: Angular Deploy gh-pages Actions
# #       # You may pin to the exact commit or the version.
# #       # uses: AhsanAyaz/angular-deploy-gh-pages-actions@26ffbdb76b46ce3d649d046f1f7f45099654cfd7
# #       uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
# #       with:
# #         # Github access token token used to deploy on gh_pages. You can find it on Github.
# #         github_access_token: b4cd65193b19b2e7c06bfdacbc39767024c7b2e2
# #         # The directory of the angular project, in which all the commands will run
# #         angular_project_dir: fuzzy-octo-pancake/
# #         # Build configuration for the angular app
# #         build_configuration: production
# #         # base href for the app
# #         base_href: /fuzzy-octo-pancake/
# #         # branch on which the angular build will be deployed
# #         deploy_branch: gh-pages
# #         # The folder in which `ng build` provides its output. This is the folder which will be deployed to the `deploy_branch`.
# #         angular_dist_build_folder: /
# #         # If the action should run 'ng lint'
# # #         run_lint: true
# #         # Will not fail the step if anything fails
# # #         skip_failure: false

jobs:
  publish:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      -
        name: Setup Node.js environment
        run: ng deploy --base-href=/fuzzy-octo-pancake/

#         name: Github Pages Deploy Action
#         uses: avinal/github-pages-deploy-action@v0.9
#         with:
          # GitHub access token with Repo Access
#           GITHUB_TOKEN: # default is ${{ github.token }}
          # java(for JavaDoc), python(For Python Site/Documentation Generators)
#           LANGUAGE: 
          # make command to generate html
#           MAKE_COMMAND: # default is make html
          # Deploy pages to which branch
#           PAGES_BRANCH: # default is gh-pages
          # Generate Site from which branch
#           BUILD_FROM: # default is master
          # folder in which generated files are stored
#           DOCS_FOLDER: # default is docs
#       -
#         name: Change Dir
#         run: cd fuzzy-octo-pancake\
#       -
#         name: Install
#         run: npm i
#       -
#         name: Build
# #         run: npm run build
#         run: ng deploy --base-href=/fuzzy-octo-pancake/
# #       -
# #         name: Gen dummy page
# #         run: |
# #           mkdir public
# #           cat > public/index.html <<EOL
# #           <!doctype html>
# #           <html>
# #             <head>
# #               <title>GitHub Pages deployedeeeee!</title>
# #             </head>
# #             <body>
# #               <p>GitHub Pages with <strong>${{ github.sha }}</strong> commit ID has been deployed through <a href="https://github.com/marketplace/actions/github-pages">GitHub Pages action</a> successfully.</p>
# #             </body>
# #           </html>
# #           EOL
#       -
#         name: Deploy to GitHub Pages
#         if: success()
#         uses: crazy-max/ghaction-github-pages@v2
#         with:
#           target_branch: gh-pages
#           build_dir: fuzzy-octo-pancake\dist\fuzzy-octo-pancake\
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

